// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8QD-8NZ8HDzOYLqvFXEZxsQUPnFjnXqo',
    appId: '1:1052200809839:web:72f3e0ba41e9f3fde2649a',
    messagingSenderId: '1052200809839',
    projectId: 'hackathon-log',
    authDomain: 'hackathon-log.firebaseapp.com',
    storageBucket: 'hackathon-log.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfUQ1t8XEACiBceqhqCtXj-IO7QR6meLA',
    appId: '1:1052200809839:android:0d1112292adecb8be2649a',
    messagingSenderId: '1052200809839',
    projectId: 'hackathon-log',
    storageBucket: 'hackathon-log.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZSyqFGKCboItVsW8q21OT5s_hXT7eBs',
    appId: '1:1052200809839:ios:739c62a9e732b4b8e2649a',
    messagingSenderId: '1052200809839',
    projectId: 'hackathon-log',
    storageBucket: 'hackathon-log.firebasestorage.app',
    iosBundleId: 'com.example.hackathonLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZSyqFGKCboItVsW8q21OT5s_hXT7eBs',
    appId: '1:1052200809839:ios:739c62a9e732b4b8e2649a',
    messagingSenderId: '1052200809839',
    projectId: 'hackathon-log',
    storageBucket: 'hackathon-log.firebasestorage.app',
    iosBundleId: 'com.example.hackathonLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8QD-8NZ8HDzOYLqvFXEZxsQUPnFjnXqo',
    appId: '1:1052200809839:web:e0e76c6d022d68dde2649a',
    messagingSenderId: '1052200809839',
    projectId: 'hackathon-log',
    authDomain: 'hackathon-log.firebaseapp.com',
    storageBucket: 'hackathon-log.firebasestorage.app',
  );
}
